---
title: "Survival Analysis of Breastfeeding / Smoking"
author: "Christopher Park"
date: "May 13, 2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load packages and import dataset
```{r}
library(survival)
library(survminer)
library(My.stepwise)
library(EnvStats)
library(ggplot2)

bf <- read.csv("breastfeed.csv")
```

## Descriptives of Variables
```{r}
# Convert categoricals to factor
bf$race <- as.factor(bf$race)
bf$poverty <- as.factor(bf$poverty)
bf$smoke <- as.factor(bf$smoke)
bf$alcohol <- as.factor(bf$alcohol)
bf$educ <- as.numeric(bf$educ)
bf$prenatal3 <- as.factor(bf$prenatal3)

# Density Plot of variables and mean for continuous variables
plot(density(bf$complete))# Much greater values of 1 over 0
plot(density(bf$length)) # Distribution positively skewed
plot(bf$race) # Number of whites is highest, followed by Others, then Blacks
plot(bf$poverty) # Greater number of mothers in poverty
plot(bf$smoke) # Mother's who smoked while pregnant around half of those who did not smoke
plot(bf$alcohol) # Mostly no alcohol consumption during pregnancy
plot(density(bf$age)) # Normally Distributed
plot(density(bf$birthyr)) # Child born mostly between 1980-1985
plot(density(bf$educ)) # Normally distributed 
plot(bf$prenatal3) # Greater number of those who did not seek out prenatal care in first three 3 months
```

## Descriptive Survival Analysis
```{r}
# Fit KM for each variable
fit.race <- survfit(Surv(length, complete)~race, data = bf, conf.type = "log-log") # conf.type log-log
fit.poverty <- survfit(Surv(length, complete)~poverty, data = bf, conf.type = "log-log") # conf.type log-log
fit.smoke <- survfit(Surv(length, complete)~smoke, data = bf, conf.type = "log-log") # conf.type log-log
fit.alcohol <- survfit(Surv(length, complete)~alcohol, data = bf, conf.type = "log-log") # conf.type log-log
fit.age <- survfit(Surv(length, complete)~age, data = bf, conf.type = "log-log") # conf.type log-log
fit.birthyr <- survfit(Surv(length, complete)~birthyr, data = bf, conf.type = "log-log") # conf.type log-log
fit.educ <- survfit(Surv(length, complete)~educ, data = bf, conf.type = "log-log") # conf.type log-log
fit.prenatal <- survfit(Surv(length, complete)~prenatal3, data = bf, conf.type = "log-log") # conf.type log-log

# Plot KM for each model
plot.race <- ggsurvplot(fit.race, bf, conf.int = T, risk.table = T, pval = T)
plot.poverty <- ggsurvplot(fit.poverty, bf, conf.int = T, risk.table = T, pval = T)
plot.smoke <- ggsurvplot(fit.smoke, bf, conf.int = T, risk.table = T, pval = T)
plot.alcohol <- ggsurvplot(fit.alcohol, bf, conf.int = T, risk.table = T, pval = T)
plot.age <- ggsurvplot(fit.age, bf, conf.int = T, risk.table = T, pval = T)
plot.birthyr <- ggsurvplot(fit.birthyr, bf, conf.int = T, risk.table = T, pval = T)
plot.educ <- ggsurvplot(fit.educ, bf, conf.int = T, risk.table = T, pval = T)
plot.prenatal <- ggsurvplot(fit.prenatal, bf, conf.int = T, risk.table = T, pval = T)
```

## Two group comparisons - Gehan Wilcoxon Test
```{r}
# Due to high number of ties the Gehan-Wilcoxon test used (Rho = 1: Wilcoxon)
log.race <- survdiff(Surv(length, complete)~race, data = bf, rho = 1) # p = 0.008
log.poverty <- survdiff(Surv(length, complete)~poverty, data = bf, rho = 1) # p = 0.9
log.smoke <- survdiff(Surv(length, complete)~smoke, data = bf, rho = 1) # p = 0.004
log.alcohol <- survdiff(Surv(length, complete)~alcohol, data = bf, rho = 1) # p = 0.2
log.age <- survdiff(Surv(length, complete)~age, data = bf, rho = 1) # p = 0.2
log.birthyr <- survdiff(Surv(length, complete)~birthyr, data = bf, rho = 1) # p = 0.1
log.educ <- survdiff(Surv(length, complete)~educ, data = bf, rho = 1) #p = 0.04
log.prenatal <- survdiff(Surv(length, complete)~prenatal3, data = bf, rho = 1) #p = 0.5
```

## Selecting Covariates - Stepwise Regression
```{r}
# Convert all variables to numeric to run stepwise regression
bf <- apply(bf, 2, as.numeric)
bf <- as.data.frame(bf)

# Stepwise regression
covariates <- c("race","poverty","alcohol", "smoke","birthyr","educ","prenatal3")
stepwise.fit <- My.stepwise.coxph(Time = "length", Status = "complete", in.variable = "age", variable.list = covariates, data = bf, sle = 0.2, sls = 0.1)

# Reconvert Selected Variables to Factors 
bf$smoke <- as.factor(bf$smoke)
bf$race <- as.factor(bf$race)
bf$poverty <- as.factor(bf$poverty)

# Base and Fully Adjusted Cox PH Models
cox.unadj <- coxph(Surv(length, complete) ~ smoke, data = bf, method = "efron") # efron approximation due to high number of ties and yields closer estimates than breslow
cox.adj <- coxph(Surv(length, complete) ~ smoke + age + birthyr + race + educ + poverty, data = bf, method = "efron")

# loglikelihood/AIC
cox.unadj$loglik[2]*(-2) # 10382
AIC(cox.unadj) # 10384
cox.adj$loglik[2]*(-2) # 10337.98
AIC(cox.adj) # 10349.98
chi2 <- cox.unadj$loglik[2]*(-2) - cox.adj$loglik[2]*(-2)
chi2
```


## Evaluating linearity of age effects
```{r}
# Age as continuous
age.cont <- coxph(Surv(length, complete) ~ smoke + age + birthyr + race + educ + poverty, data = bf, method = "efron")
# age as sqrt
bf$age_sqrt <- sqrt(bf$age)
age.sqrt <- coxph(Surv(length, complete) ~ smoke + age_sqrt + birthyr + race + educ + poverty, data = bf, method = "efron")
# age as cat
quantile(bf$age)
bf$age_cat <- bf$age
bf$age_cat[bf$age <= 20] <- 1
bf$age_cat[bf$age > 20 & bf$age < 23] <- 2
bf$age_cat[bf$age >= 23] <- 3
age.cat <- coxph(Surv(length, complete) ~ smoke + as.factor(age_cat) + birthyr + race + educ + poverty, data = bf, method = "efron")
# age as ordinal
age.ordinal <- coxph(Surv(length, complete) ~ smoke + age_cat + birthyr + race + educ + poverty, data = bf, method = "efron")
# age as linear, quad
bf$age_quad <- bf$age^2
age.quad <- coxph(Surv(length, complete) ~ age_quad + age + birthyr + smoke + race + educ + poverty, data = bf, method = "efron")
# age as linear, quad, cubic
bf$age_cubic <- bf$age^3
age.cubic <- coxph(Surv(length, complete) ~ smoke + age_cubic + age_quad + age + birthyr + race + educ + poverty, data = bf, method = "efron")

# Loglikelihood and AIC
age.cont$loglik[2]*(-2) # 10343.12
age.sqrt$loglik[2]*(-2) # 10343.08
age.cat$loglik[2]*(-2) # 10343.48
age.ordinal$loglik[2]*(-2) # 10342.71
age.quad$loglik[2]*(-2) # 10342.94
age.cubic$loglik[2]*(-2) # 10337.57
AIC(age.cont, age.sqrt, age.cat, age.ordinal, age.quad, age.cubic)
# Final Cox Model
cox.final <- coxph(Surv(length, complete) ~ smoke + age_cubic + age_quad + age + birthyr + race + educ + poverty, data = bf, method = "efron")
summary(cox.final)
AIC(cox.final)
```
## Diagnostics
```{r}
# Break continuous into groups
quantile(bf$age_quad)
bf$quad_cat <- bf$age_quad
bf$quad_cat[bf$age_quad <= 400] <- 1
bf$quad_cat[bf$age_quad > 400 & bf$age_quad <= 529] <- 2
bf$quad_cat[bf$age_quad > 529] <- 3
bf$quad_cat <- as.factor(bf$quad_cat)

quantile(bf$age_cubic)
bf$cubic_cat <- bf$age_cubic
bf$cubic_cat[bf$age_cubic <= 8000] <- 1
bf$cubic_cat[bf$age_cubic > 8000 & bf$age_cubic <= 12167] <- 2
bf$cubic_cat[bf$age_cubic > 12167] <- 3
bf$cubic_cat <- as.factor(bf$cubic_cat)

quantile(bf$birthyr)
bf$birthyr_cat <- bf$birthyr
bf$birthyr_cat[bf$birthyr <= 80] <- 1
bf$birthyr_cat[bf$birthyr > 80 & bf$birthyr < 84] <- 2
bf$birthyr_cat[bf$birthyr >= 84] <- 3
bf$birthyr_cat <- as.factor(bf$birthyr_cat)

quantile(bf$educ)
bf$educ_cat <- bf$educ
bf$educ_cat[bf$educ < 12] <- 1
bf$educ_cat[bf$educ >= 12 & bf$educ <= 13] <- 2
bf$educ_cat[bf$educ > 13] <- 3
bf$educ_cat <- as.factor(bf$educ_cat)

## Model Diagnostics
ftest <- cox.zph(cox.final)
ftest
dev <- ggcoxzph(ftest)
dev

## plot against predicted values
ggadjustedcurves(cox.final, variable = "age", data = bf)
ggadjustedcurves(cox.final, variable = "age_cubic", data = bf)
ggadjustedcurves(cox.final, variable = "age_quad", data = bf)
ggadjustedcurves(cox.final, variable = "birthyr_cat", data = bf)
ggadjustedcurves(cox.final, variable = "smoke", data = bf)
ggadjustedcurves(cox.final, variable = "race", data = bf)
ggadjustedcurves(cox.final, variable = "educ_cat", data = bf)
ggadjustedcurves(cox.final, variable = "poverty", data = bf)
ggcoxdiagnostics(cox.final, type = "martingale", ox.scale = "time")

## Plot Loglog vs log
KM_fit <- survfit(Surv(log(length), complete) ~ smoke, data = bf)
par(mfrow = c(1, 2))
plot(KM_fit, xlab = "Weeks", ylab = "Survival", col = 1:2)
legend("topright", levels(bf$smoke), lty = 1, col = 1:2, bty = "n")

plot(KM_fit, fun = function (s) log(-log(s)), xlab = "log(Weeks)", 
     ylab = "log(-log(Survival))", col = 1:2)

## Power Calculations
coxph(Surv(length, complete)~smoke, bf)
(4*(1.96+0.84)^2)/(abs(log(1.254846))^2)
```
